using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MGX_Discord_Bot.EModules.Holders.CommandHolders
{
    class FactHolder
    {
        private List<string> Facts = new List<string>()
        {
            {"The scientific term for brain freeze is “sphenopalatine ganglioneuralgia”."},
            {"Canadians say “sorry” so much that a law was passed in 2009 declaring that an apology can’t be used as evidence of admission to guilt."},
            {"Back when dinosaurs existed, there used to be volcanoes that were erupting on the moon."},
            {"The only letter that doesn’t appear on the periodic table is J."},
            {"One habit of intelligent humans is being easily annoyed by people around them, but saying nothing in order to avoid a meaningless argument."},
            {"If a Polar Bear and a Grizzly Bear mate, their offspring is called a “Pizzy Bear”."},
            {"In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi responded by notifying Coca-Cola."},
            {"There were two AI chatbots created by Facebook to talk to each other, but they were shut down after they started communicating in a language they made for themselves."},
            {"Nintendo trademarked the phrase “It’s on like Donkey Kong” in 2010."},
            {"Calling “shotgun” when riding in a car comes from the term “shotgun messenger”.Dog Riding Shotgun. This term which was used to refer to the guard who sat next to the Stagecoach driver. The guards would use a shotgun to keep robbers and criminals away. It made its way into society due to Hollywood’s love of Western flicks."},
            {"The famous line in Titanic from Leonardo DiCaprio, “I’m king of the world!” was improvised."},
            {"A single strand of Spaghetti is called a “Spaghetto”."},
            {"There is actually a difference between coffins and caskets – coffins are typically tapered and six-sided, while caskets are rectangular."},
            {"Sunflowers can help clean radioactive soil. Japan is using this to rehabilitate Fukashima. Almost 10,000 packets of sunflower seeds have been sold to the people of the city."},
            {"To leave a party without telling anyone is called in English, a “French Exit”. In French, it’s called a “partir à l’anglaise”, to leave like the English."},
            {"If you cut down a cactus in Arizona, you be penalized up to 25 years in jail. It is similar to cutting down a protected tree species."},
            {"In Colorado, USA, there is still an active volcano. It last erupted about the same time as the pyramids were being built in Egypt."},
            {"The first movie ever to put out a motion-picture soundtrack was Snow White and the Seven Dwarves."},
            {"If you point your car keys to your head, it increases the remote’s signal range."},
            {"In order to protect themselves from poachers, African Elephants have been evolving without tusks, which unfortunately also hurts their species."},
            {"The scientific name for Giant Anteater is Myrmecophaga Tridactyla. This means “ant eating with three fingers”."},
            {"Originally, cigarette filters were made out of cork, the look of which was incorporated into today’s pattern."},
            {"In 1923, a jockey suffered a fatal heart attack but his horse finished and won the race, making him the first and only jockey to win a race after death."},
            {"At birth, a baby panda is smaller than a mouse."},
            {"Iceland does not have a railway system."},
            {"The largest known prime number has 17,425,170 digits. The new prime number is 2 multiplied by itself 57,885,161 times, minus 1."},
            {"Forrest Fenn, an art dealer and author, hid a treasure chest in the Rocky Mountains worth over 1 million dollars. It still has not been found."},
            {"The lead singer of The Offspring started attending school to achieve a doctorate in molecular biology while still in the band. He graduated in May 2017."},
            {"The world’s largest grand piano was built by a 15-year-old in New Zealand."},
            {"In order to keep Nazis away, a Polish doctor faked a typhus outbreak. This strategy saved 8,000 people."},
            {"After the release of the 1996 film Scream, which involved an anonymous killer calling and murdering his victims, Caller ID usage tripled in the United States."},
            {"The spiked dog collar was invented by the Ancient Greeks to protect their dogs from wolf attacks."},
            {"Jack Daniel (the founder of the whiskey) died from kicking a safe. When he kicked it, he broke his toe which got infected. He eventually died from blood poisoning."},
            {"There is a boss in Metal Gear Solid 3 that can be defeated by not playing the game for a week; or by changing the date."},
            {"The Roman – Persian wars are the longest in history, lasting over 680 years. They began in 54 BC and ended in 628 AD."},
            {"Elton John tried to commit suicide once by sticking his head in an oven with the gas on low and windows open. He was found and stopped by his best friend Bernie Taupin."},
            {"The Buddha commonly depicted in statues and pictures is a different person entirely. The real Buddha was actually incredibly skinny because of self-deprivation."},
            {"If you translate “Jesus” from Hebrew to English, the correct translation is “Joshua”. The name “Jesus” comes from translating the name from Hebrew, to Greek, to Latin, to English."},
            {"Ed Sheeran bought a ticket to LA with no contacts. He was spotted by Jamie Foxx, who offered him the use of his recording studio and a bed in his Hollywood home for six weeks."},
            {"German Chocolate Cake is named after an American baker by the name of Samuel German."},
            {"The first service animals were established in Germany during World War I. References to service animals date as far back as the mid-16th Century."},
            {"An 11-year-old girl proposed the name for Pluto after the Roman god of the Underworld."},
            {"The voice actor of SpongeBob and the voice actor of Karen, Plankton’s computer wife, have been married since 1995."},
            {"An Italian banker, Gilberto Baschiera is considered a modern-day Robin Hood. Over the course of 7 years, he secretly diverted 1 million euros to poorer clients from the wealthy ones so they could qualify for loans. He made no profit and avoided jail in 2018 due to a plea bargain."},
            {"Octopuses and squids have beaks. The beak is made of keratin – the same material that a bird’s beak, and our fingernails are made of."},
            {"An estimated 50% of all gold ever mined on Earth came from a single plateau in South Africa: Witwatersrand."},
            {"75% of the world’s diet is produced from just 12 plant and five different animal species."},
            {"The original Star Wars premiered on just 32 screens across the U.S. in 1977. This was to produce buzz as the release widened to more theaters."},
            {"The British government coined the slogan, “Keep Calm and Carry on” during World War 2 in order to motivate citizens to stay strong."},
            {"Apple paid a couple $1.7 million dollars for their plot of land, which was only worth $181,700."},
            {"Tirana, the capital of Albania has a lot of things in common with other European capitals – except one.  It’s one of two capitals without a McDonalds. The second is Vatican City."},
            {"Joe Arridy had an IQ of 46 and is known as the “happiest prisoner on death row”. He went into the gas chamber with a smile. It turned out he was innocent."},
            {"The largest Japanese population outside of Japan stands at 1.6 million people who live in Brazil."},
            {"IKEA is an acronym which stands for Ingvar Kamprad Elmtaryd Agunnaryd, which is the founder’s name, farm where he grew up, and hometown."},
            {"In 2009, Stephen Hawking held a reception for time travelers, but didn’t publicize it until after. This way, only those who could time travel would be able to attend. Nobody else attended."},
            {"Violin bows are commonly made from horse hair."},
            {"There are less than 30 ships in the Royal Canadian Navy which is less than most third-world countries."},
            {"Larry the Cable Guy’s real name is Daniel Lawrence Whitney. His notable Southern accent is fake – he was born and raised in the mid-west, not the South."},
            {"The youngest Pope in history was Pope Benedict IX who was 11 years old at the time of election. He is also the only person to have been the Pope more than once."},
            {"In Svalbard, a remote Norwegian island, it is illegal to die."},
            {"This is because bodies are unable to be buried safely due to the permafrost on the ground. If you are about to die, they fly you back to mainland Norway to pass on there."},
            {"Costa Coffee employs Gennaro Pelliccia as a coffee taster, who has had his tongue insured for £10 million since 2009."},
            {"Johnny Cash took only three voice lessons before his teacher advised him to stop taking lessons and to never deviate from his natural voice."},
            {"During the Prohibition era, the U.S. Government allowed Whiskey to be sold through pharmacies. As a result, Walgreens grew from 20 retail stores to almost 400."},
            {"People who post their fitness routine to Facebook are more likely to have psychological problems."},
            {"Medieval chastity belts are a myth. A great majority of examples now existing were made in the 18th and 19th centuries as jokes."},
            {"Nowadays, millionaires with just $1 million isn’t considered wealthy anymore by most Americans. Now, the typical American sees at least $2.4 million as wealthy."},
            {"Hanna-Barbera pitched The Flintstones to networks for 8 weeks before it was finally picked up. It became the first ever animated show to air during primetime."},
            {"In 1325, two Italian city states fought over a bucket which resulted in 2,000 deaths. It started when two soldiers stole a bucket from a well from the city center."},
            {"Although GPS is free for the world to use, it costs $2 million per day to operate. The money comes from American tax revenue."},
            {"Standing around burns calories. On average, a 150 pound person burns 114 calories per hour while standing and doing nothing."},
            {"In World War II, Germany tried to collapse the British economy by dropping millions of counterfeit bills over London."},
            {"Playboy has been publishing braille versions of their magazines since 1970, however no pictorial representations are included."},
            {"The color red doesn’t really make bulls angry; they are color-blind."},
            {"65% of autistic kids are left-handed, and only 10% of people in general are left-handed."},
            {"When Space Invaders was created, Tomohiro Nishikado left in the lag caused by more invaders on the screen in order to create greater difficulty in the games."},
            {"Herring fish communicate by using flatulence."},
            {"Until 2016, the “Happy Birthday” song was not for public use. Meaning, prior to 2016, the song was copyrighted and you had to pay a license to use it."},
            {"When mice live in the wild, they typically only live for about six months."},
            {"There is a punctuation mark used to signify irony or sarcasm that looks like a backwards question mark ⸮"},
            {"During the cremation process of a 500 pound body, the corpse was so obese that it set the crematorium on fire."},
            {"When George Washington died, Napoleon Bonaparte of France gave a personal eulogy and ordered a ten day mourning period for France."},
            {"The Hobbit has been published in two editions. In the first edition, Gollum willingly bet on his ring in the riddle game."},
            {"For nearly 60 years, Texas didn’t have an official state flag between 1879 & 1933. During that time, the Lone Star flag was the active, but unofficial flag."},
            {"A wildlife technician, Richard Thomas, took the famous tongue twister, “how much wood would a woodchuck chuck if a woodchuck could chuck wood” and calculated a rough estimate of what the answer would actually be. It came out to be around 700 pounds."},
            {"Red Solo cups are a common souvenir to bring back from the United States. The novelty comes from the cups being used in many party scenes in movies."},
            {"Swedish meatballs originated from a recipe King Charles XII brought back from Turkey in the early 1800s."},
            {"Saint Lucia is the only country in the world named after a woman."},
            {"Ben & Jerry’s has an online flavor graveyard for their 10 discontinued ice cream flavors. Each one has a photo, life span, and epitaph."},
            {"Scientists discovered sharks that are living in an active underwater volcano. Divers cannot investigate because they would get burns from the acidity and heat."},
            {"There are times when Pluto is closer to the Sun than Neptune – one of these timelines was from 1979 to 1999."},
            {"There is a town in Nebraska called Monowi with a population of one. The only resident is a woman who is the Mayor, Bartender and Librarian."},
            {"The Ethiopian calendar is 7.5 years behind the Gregorian calendar due to the fact that it has 13 months."},
            {"In 1994, the company who had a patent on GIFs tried to charge a fee for using GIFS. The PNG was invented as an alternative, and the company backed down."},
            {"China is spending $3 billion dollars to build panda shaped solar farms in order to get more young people interested in renewable energy."},
            {"While hunting, stoats go crazy jumping, spinning, and twisting to get a rabbits attention. This hypnotizes the rabbit until the stoat gets close enough to attack."},
            {"The average American child is given $3.70 per tooth that falls out."},
            {"To properly write adjectives in order, you would list them by amount, value, size, temperature, age, shape, color, origin, and material."},
            {"The world’s first motel is in San Luis Obispo. Built in 1925. When opened, it cost $1.25 for a two-room bungalow with a kitchen and a private adjoining garage."},
            {"Scotland was one of the few countries able to hold off being conquered by the Romans in the first century A.D."},
            {"I Will Always Love You was originally written and recorded in 1973 by Dolly Parton. It was written as a farewell to her mentor of seven years."},
            {"“Opposites attract” is a common myth. People are actually attracted to people who look like family members, or those with a similar personality type."},
            {"Llamas can be used as guards against coyote attacks on sheep herds. Studies have proven that just one guard llama is an effective protector and can even kill the attacking coyotes."},
            {"The unique smell of rain actually comes from plant oils, bacteria, and ozone."},
            {"Vanilla flavoring is sometimes made with the urine of beavers."},
            {"If you heat up a magnet, it will lose its magnetism."},
            {"The most expensive virtual object is “Club NEVERDIE” in the Entropia Universe which is worth $635,000. It was originally bought at $10,000."},
            {"Researches have found that flossing your teeth can help your memory. Flossing prevents gum disease, which prevents stiff blood vessels, which cause memory issues."},
            {"Cruise ships have morgues that can store up to 10 bodies at once. The average amount of people that die on cruise ships per year is 200."},
            {"Birds are the closest living relatives of crocodilians, as well as the descendants of extinct dinosaurs with feathers. This makes them the only surviving dinosaurs."},
            {"Small as they may be, ladybugs have a unique smell that humans are incredibly sensitive to."},
            {"During WWII, a U.S. naval destroyer won a battle against a Japanese submarine by throwing potatoes at them. The Japanese thought they were grenades."},
            {"The Marshal Mathers foundation for at-risk and disadvantaged youth, was founded by Eminem."},
            {"Since 1955, 50% of the population of Niger is consistently under 16 years old. The total current population is 21,600,000."},
            {"The author of Mary Had a Little Lamb, Sarah Josepha Hale, is most responsible for the creation of Thanksgiving being a national holiday."},
            {"The oldest unopened bottle of wine was found in a Roman tomb that is over 1,650 years old."},
            {"Chicken Run is the highest-grossing stop motion animated film, even beating The Nightmare Before Christmas."},
            {"Nobody knows how the Academy Awards came to be referred to as the Oscars. The earliest mention was 1932, and was made official in 1939."},
            {"More tornadoes occur in the United Kingdom per square mile than any other country in the world."},
            {"Owners of personalized license plates in Uganda are facing a tax increase of over 300%, which will raise the tax from $1,498 to $5,992."},
            {"Popularized by the Shakespeare play, many people think Julius Caesar’s last words were “And you, Brutus?” In reality, he said “You too, my child?”"},
            {"Times Square was originally called Longacre square until it was renamed in 1904 after The New York Times moved its headquarters to the newly built Times Building."},
            {"Daniel Craig was an anonymous Storm Trooper in Star Wars: The Force Awakens. Originally, he denied his cameo and claimed he wouldn’t bother being an extra in a movie."},
            {"Queen Elizabeth has a personal net worth of 425 million dollars. That includes the $65 million Sandringham House and $140 million Balmoral Castle."},
            {"Although there is currently no drug proven to make someone tell the truth, some countries like Russia, Canada, and India use truth serums."},
            {"Only primates, humans, and opossums have opposable thumbs. Out of these, the opossum is the only one with no thumbnail."},
            {"One of the World Trade Center’s was built to be 1,776 feet tall on purpose to reference the year the Declaration of Independence was signed."},
            {"The word “kimono”, literally means a “thing to wear”. Ki is “wear”, and mono is “thing”."},
            {"There is a statue of Tesla in Silicon Valley that radiates free Wi-Fi. It was done as an homage to his vision for wireless communication."},
            {"It snows metal on planet Venus! There are two types that have been found, galena and bismuthinite."},
            {"Tic Tacs got their name from the sound they make when they are tossed around in their container."},
            {"Only official members of a federally accepted Native American tribe may legally possess or collect eagle feathers. If a normal citizen has one, it is illegal."},
            {"Bi-weekly has two different definitions: Twice a week, or once every two weeks."},
            {"Mona Lisa was stolen from the Louvre in 1911, which drew more visitors to see the empty space than the actual painting."},
            {"There is an insurance policy issued against alien abduction. Around 50,000 policies have been sold, mainly to residents of the U.S. and England."},
            {"Volvo invented the three-point seatbelt, then gave the invention away for free. They decided it was too important of an invention to keep to themselves."},
            {"In 2005, Connecticut was accidentally issued an Emergency Alert to evacuate the entire state. Only about 1% of the people actually tried to leave."},
            {"An 18-year old with dwarfism played the 8-year-old Grinch in The Grinch (2000). He passed away two years after the film was released."},
            {"Rebecca Felton was the first woman to ever serve for the United States Senate – but she only served for one day."},
            {"Websters Dictionary accidentally had a word that didn’t exist in it for five years – “Dord”."},
            {"Amber colored rear turn signals are statistically proven to reduce collisions by about 28%."},
            {"Roselle, a guide dog, lead her blind owner down 78 flights of stairs during 9/11. The descent took about an hour and they both safely made it out."},
            {"It is supposedly thought by Russians that eating ice cream will keep you warm."},
            {"Somebody hid an episode of South Park inside Tiger Woods 99 as an Easter egg, causing EA to do a massive recall."},
            {"Madagascar once was a stomping ground for lemurs which were the size of today’s gorillas."},
            {"Underneath the streets of Beijing, there are over a million people who live in nuclear bunkers."},
            {"The full name of the famous Chuck E. Cheese’s mouse is Charles Entertainment Cheese."},
            {"If you add up the numbers on a roulette wheel, you will get 666."},
            {"The day after Thanksgiving is called “Brown Friday” by plumbers in America because it is their busiest day of the year."},
            {"The wife of Anthony Perkins, the original Norman Bates, Berry Berenson died as a result of being a passenger on one of the 9/11 planes."},
            {"The thumbs up sign is believed to have originated from Chinese pilots. It was used to communicate with the ground crew before take-off."},
            {"In Toy Story 2 in the scene where Buzz gives a speech in front of the American flag, the flag was edited to be a globe for release in non-American countries."},
            {"The tallest mountain in our solar system, Olympic Mons, is 3 times taller than Mount Everest."},
            {"Batman and Predator exist in the same fictional universe. Since 1991, they have been featured together in three comic books."},
            {"A study from Harvard University finds that having no friends can be just as deadly as smoking. Both effect levels of a blood-clotting protein."},
            {"In South Dakota, you can get a driver’s permit at age 14 with parental consent. Once you turn 16, you can get your license."},
            {"The Backpack Kid’s real name is Russell Horning."},
            {"In 2017, Adidas sold over 1 million pairs of shoes made from recycled ocean plastic, each pair taking 11 plastic bottles to make."},
            {"The British Pound is the world’s oldest currency still in use at 1,200 years old. The pound has been an identity as a symbol of British sovereignty."},
            {"The world’s smallest mammal, a Bumblebee Bat, weights about the same as a U.S. dime. Native to Myanmar and Thailand, these bats are endangered."},
            {"As of December 2018, The Itchy & Scratchy Show that takes place within The Simpsons, has 107 episodes."},
            {"Will Smith owed $2.8 Million to the IRS and almost went bankrupt, just before he signed the contract for The Fresh Prince Of Bel-Air."},
            {"The Great Pyramid of Giza actually has eight sides, rather than four. All of the other pyramids have just four sides."},
            {"English is not native to the British Isles. It was brought to Britain in the mid 5th to 7th Centuries by German, Danish, and Dutch settlers."},
            {"When we’re born, the only innate fears we have are the fear of falling, and the fear of loud sounds. All other fears are learned."},
            {"In Korea, there is a breed of dog called a Sapsali which was originally thought to banish ghosts and evil spirits."},
            {"Qantas Airways once powered an interstate flight on cooking oil. This marked Australia’s first commercial flight using sustainably derived biofuel."},
            {"Berries are simple fruits stemming from one flower. This means that pineapples, bananas, watermelon, pumpkins, and avocados are berries."},
            {"One horse can have approximately 15 horsepower. Horsepower is about 746 watts. The term was coined in the late 18th Century."},
            {"The Leaning Tower of Piza is tilted because of the soft soil that it’s built on – which has also protected it from at least 4 powerful earthquakes."},
            {"All the paint on the Eiffel Tower weighs the same as ten elephants. It gets repainted every seven years without closing to the public."},
        };

        public List<string> ReturnAllFacts()
        {
            return Facts;
        }
    }
}
